### ISSUE TITLE
Clicking on the users returns not found

### ISSUE THREAD

**Issue by aminya** [ryansolid/marko-hackernews#1]
Example:
https://marko-hackernews.herokuapp.com/stories/users/max_

**Comment by ryansolid** [comment]
I see hmm.. probably need better error handling. Or maybe its a pattern match issue. Most user pages seem to work but not that one.

EDIT I see it. The URL is wrong. There must be a bad link somewhere. Maybe on the Story page. Its relative instead of absolute.

**Comment by ryansolid** [comment]
Ok fixed now. Thanks.
